# Generated by Django 6.1.1 on 2026-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre y apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('leido', models.BooleanField(default=False, verbose_name='leído')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-creado'],
            },
        ),
    ]
