# Generated by Django 6.1.1 on 2026-10-05 23:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de la consulta')),
                ('motivo', models.CharField(max_length=200, verbose_name='motivo de la consulta')),
                ('diagnostico', models.TextField(verbose_name='diagnóstico')),
                ('indicaciones', models.TextField(blank=True, verbose_name='indicaciones')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='cargado el')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_historia', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_historia', to='clinica.profesional')),
            ],
            options={
                'verbose_name': 'entrada de historia clínica',
                'verbose_name_plural': 'entradas de historia clínica',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
