# Generated by Django 6.1.1 on 2026-10-06 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('slug', models.SlugField(help_text='Se completa solo con el titulo. Es lo que va en la direccion.', max_length=100, unique=True)),
                ('resumen', models.CharField(help_text='Una o dos oraciones. Se muestra en las tarjetas del listado.', max_length=200)),
                ('contenido', models.TextField(help_text='Deja un renglon en blanco para separar los parrafos.')),
                ('imagen', models.ImageField(blank=True, upload_to='novedades/')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de publicacion')),
                ('publicada', models.BooleanField(default=True, help_text='destildala para guardar la nota como borrador')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
                'ordering': ['-fecha_publicacion', '-pk'],
            },
        ),
    ]
