# Generated by Django 6.1.1 on 2026-10-07 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='contenido',
            field=models.TextField(help_text='Dejá un renglón en blanco para separar los párrafos.'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='publicada',
            field=models.BooleanField(default=True, help_text='Destildala para guardar la nota como borrador.'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='slug',
            field=models.SlugField(help_text='Se completa solo con el título. Es lo que va en la dirección.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
    ]
