# Generated by Django 6.1.1 on 2026-10-05 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo de la consulta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clinica.profesional')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['fecha', 'hora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('profesional', 'fecha', 'hora'), name='turno_unico_por_profesional', violation_error_message='Ese profesional ya tiene un turno en ese día y horario.')],
            },
        ),
    ]
